server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    database-plataform: org.hibertnate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-alto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander

